services:
  worker-service:
    build:
      context: ./worker-service
      dockerfile: Dockerfile
    container_name: worker-service
    ports:
      - "0.0.0.0:8081:8081"
    mem_limit: 536m
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - API_SERVICE_URL=http://${API_EC2_PRIVATE_IP:-api-service}:8080
      - INTERNAL_SECRET=${INTERNAL_SECRET}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - codepad-projects:/data/projects
    restart: unless-stopped

  runtime-image:
    image: codepad-runtime:latest
    build:
      context: ./worker-service/docker/codepad-runtime
    profiles:
      - env-setup

volumes:
  codepad-projects:
