services:
  postgres:
    image: postgres:16-alpine
    container_name: codepad-postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "127.0.0.1:5432:5432"
    mem_limit: 512m
    volumes:
      - pgdata-local:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-codepad_db}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks: [codepad-net]

  redis:
    image: redis:7-alpine
    container_name: codepad-redis
    ports:
      - "127.0.0.1:6379:6379"
    mem_limit: 128m
    networks: [codepad-net]

  api-service:
    build:
      context: ./api-service
    container_name: codepad-api
    ports:
      - "127.0.0.1:8080:8080"
    mem_limit: 1024m
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/${DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - WORKER_URL=http://worker-service:8081
      - WORKER_WS_URL=ws://worker-service:8081
      - INTERNAL_SECRET=${INTERNAL_SECRET}
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
      - FIREBASE_SERVICE_ACCOUNT_BASE64=${FIREBASE_SERVICE_ACCOUNT_BASE64}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    networks: [codepad-net]

  worker-service:
    build:
      context: ./worker-service
    container_name: codepad-worker
    ports:
      - "127.0.0.1:8081:8081"
    mem_limit: 1024m
    environment:
      - API_SERVICE_URL=http://api-service:8080
      - INTERNAL_SECRET=${INTERNAL_SECRET}
      - PROJECTS_ROOT=/data/projects
      - POOL_SIZE=${POOL_SIZE:-3}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - codepad-projects:/data/projects
    networks: [codepad-net]

  runtime-image:
    image: codepad-runtime:latest
    build:
      context: ./worker-service/docker/codepad-runtime
    profiles:
      - env-setup

#  frontend:
#    build:
#      context: ./codepad
#      args:
#        - NEXT_PUBLIC_API_URL=http://localhost:8080
#        - NEXT_PUBLIC_FIREBASE_API_KEY=${NEXT_PUBLIC_FIREBASE_API_KEY}
#        - NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN}
#        - NEXT_PUBLIC_FIREBASE_PROJECT_ID=${NEXT_PUBLIC_FIREBASE_PROJECT_ID}
#        - NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET}
#        - NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID}
#        - NEXT_PUBLIC_FIREBASE_APP_ID=${NEXT_PUBLIC_FIREBASE_APP_ID}
#        - NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=${NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID}
#    container_name: codepad-frontend
#    ports:
#      - "3000:3000"
#    depends_on:
#      - api-service
#    networks: [codepad-net]

volumes:
  pgdata-local:
  codepad-projects:

networks:
  codepad-net:
    driver: bridge
